

# Nom du site
title: "Arnaud BONNEFOI - CV"


url: "https://ton-utilisateur.github.io/ton-depot"

# Thème à utiliser 
theme: jekyll-theme-minimal  

# Description du site
description: "CV en ligne d'Arnaud BONNEFOI"



# Plugins de Jekyll 
plugins:
  - jekyll-feed
  - jekyll-seo-tag




language: "fr"


paginate: 5  # Nombre d'articles par page dans un blog


footer:
  text: "Copyright © Arnaud BONNEFOI - 2024"

